### PR TITLE
Added Option to select Cognitive Service Kind & Disable Azure Search

### PR DESCRIPTION
**Pull request by marvinbuss**
**This PR fixes**
* This PR will add the option for users to select a specific Cognitive Service Kind for the deployment. Before, we deployed a default kind. Now there is the option in the Portal and in Bicep to select the Kind for this deployment.
* Updated API version of app insights.
* Linting
* Here is a screenshot of the Portal experience:
image

### CODE REVIEW

**Review by marvinbuss — COMMENTED** [review]
LGTM!

**Review by marvinbuss — COMMENTED** [review]
LGTM!

**Review by marvinbuss — COMMENTED** [review]
LGTM!

**Review by marvinbuss — COMMENTED** [review]
LGTM!

**Comment by marvinbuss** [comment]
Proof that this works:
image
image

**Review by marvinbuss — COMMENTED** [review]
LGTM!

**Review by andrehass — DISMISSED** [review]
Looks good

**Review by marvinbuss — COMMENTED** [review]
LGTM!

**Review by andrehass — APPROVED** [review]
Looks good

**Review by marvinbuss — COMMENTED** [review]
LGTM!

**Review by esbran — APPROVED** [review]
Looks good

**Pull request merged**
