### PR TITLE
Add Service Endpoint Guidance in Docs & Portal

### PR DESCRIPTION
**Pull request by marvinbuss**
**This PR fixes**
Add Service Endpoint Guidance in Docs and Portal for Azure Machine Learning. Azure Machine Learning has specific networking requirements today and hence we need to provide additional guidance for users, who want to use this template.

### CODE REVIEW

**Review by marvinbuss — COMMENTED** [review]
LGTM!

**Review by sasever — CHANGES_REQUESTED** [review]
Line 81  would be better and more formal  if 'therefore this configuration must be done manually'
instead 'hence this must be setup manually'

**Comment by marvinbuss** [comment]
Thanks @sasever. I Also included another link which explains how this is configured.

**Review by sasever — APPROVED** [review]
Good to go, Much better with the link.

**Comment by marvinbuss** [comment]
> Good to go, Much better with the link.

Thanks for the quick response. 🥇

**Pull request merged**
